---

- name: install tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tcpdump
    - lsof
    - bind-utils
    - tmux
    - strace
    - ltrace
    - yum-plugin-changelog
    - pciutils
    - man-pages
    - telnet
